title: The 73rd Page
description: The answer lies on page 73
show_downloads: false

#
# Jekyll Settings
#
permalink: /archive/:year/:month/:day/:title/
paginate: 20
paginate_path: "page/:num"
category_dir: categories