#
# Blog Settings
#
author: Christopher Tobin
title: The 73rd Page
subtitle: The answer lies on page 73
description: The answer lies on page 73
url: https://sevenzerothree.github.io/The-73rd-Page/
gravatar_url: https://2.gravatar.com/avatar/d531eea053a5963f5463037fc7732a2e

# Github repositories
github_user: sevenzerothree
github_repo_url: https://github.com/sevenzerothree/The-73rd-Page/

# Twitter
twitter_user: sevenzer0three
twitter:
username: sevenzer0three
twitter_tweet_button: true

#
# Jekyll Settings
#
permalink: /archive/:year/:month/:day/:title/
paginate: 20
paginate_path: "page/:num"
category_dir: categories

gems:
  - jekyll-redirect-from
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-feed