#
# Blog Settings
#
theme: jekyll-theme-dinky
title: The 73rd Page
description: The answer lies on page 73
show_downloads: false

# Github repositories
github_user: sevenzerothree
github_repo_url: https://github.com/sevenzerothree/The-73rd-Page

#
# Jekyll Settings
#
permalink: /archive/:year/:month/:day/:title/
paginate: 20
paginate_path: "page/:num"
category_dir: categories